CREATE TABLE "entry_fields" (
  "id" SERIAL PRIMARY KEY,
  "calculation_type_id" int NOT NULL,
  "user_email" varchar NOT NULL,
  "calculation_date" date NOT NULL,
  "park_id" int NOT NULL,
  "asset_value" int,
  "inventory_value" int,
  "tax_asset_value" int,
  "asset_increase_percentage" int,
  "park_home_number" int,
  "vat" boolean DEFAULT false,
  "ground" boolean DEFAULT false,
  "squarem2" int,
  "constructions_year" date,
  "renovation_percentage" int,
  "yearly_revenue" int,
  "yearly_revenue_increase_perc" int,
  "asset_loan" int,
  "loan_interest" int,
  "is_deleted" boolean DEFAULT false,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL DEFAULT (now()),
  CONSTRAINT fk_entry_fields_calculation_type FOREIGN KEY (calculation_type_id) REFERENCES calculation_type(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_entry_fields_park FOREIGN KEY (park_id) REFERENCES park(id) ON UPDATE CASCADE ON DELETE RESTRICT
);