CREATE TABLE "park" (
  "id" SERIAL PRIMARY KEY,
  "brand_id" int NOT NULL,
  "name" varchar UNIQUE NOT NULL,
  "country_id" int DEFAULT NULL,
  "validated" boolean DEFAULT false,
  "is_deleted" boolean DEFAULT false,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "updated_at" timestamp NOT NULL DEFAULT (now()),
  CONSTRAINT fk_park_brand FOREIGN KEY (brand_id) REFERENCES brand(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_park_country FOREIGN KEY (country_id) REFERENCES country(id) ON UPDATE CASCADE ON DELETE RESTRICT
);

INSERT INTO park (brand_id,name,validated) 
VALUES 
(1, 'Coldenhove', true),
(1, 'De Vlinderhoeve', true),
(1, 'Heideheuvel', true),
(1, 'Heihaas', true),
(1, 'Landgoed ''t Loo', true),
(1, 'Miggelenberg', true),
(1, 'Rabbit Hill', true),
(1, 'Stroombroek', true),
(1, 'Hof van Saksen', true),
(1, 'Aelderholt', true),
(1, 'De Bloemert', true),
(1, 'Drentse Lagune', true),
(1, 'Het Land van Bartje', true),
(1, 'Hunerwold State', true),
(1, 'Orveltermarke', true),
(1, 'PUUR Exloo', true),
(1, 'De Vlegge', true),
(1, 'Landgoed De Elsgraven', true),
(1, 'Landgoed De Hellendoornse Berg', true),
(1, 'Sallandse Heuvelrug', true),
(1, 'Twenhaarsveld', true),
(1, 'Waterresort Blocksyl', true),
(1, 'De Vers', true),
(1, 'Duc de Brabant', true),
(1, 'Het Vennenbos', true),
(1, 'Kaatsheuvel', true),
(1, 'Klein Oisterwijk', true),
(1, 'De Lommerbergen', true),
(1, 'De Waufsberg', true),
(1, 'Domein De Schatberg', true),
(1, 'Hoog Vaals', true),
(1, 'Kasteeldomein De Cauberg', true),
(1, 'Landgoed Aerwinkel', true),
(1, 'Marina Resort Well', true),
(1, 'Reevallis', true),
(1, 'Beach Resort Ooghduyne', true),
(1, 'Berger Duinen', true),
(1, 'Gooise Heide', true),
(1, 'Residence Berger Duinen', true),
(1, 'Residence Westduin', true),
(1, 'De Reeuwijkse Plassen', true),
(1, 'Strand Resort Ouddorp Duin', true),
(1, 'Zuytland Buiten', true),
(1, 'Duinpark ''t Hof van Haamstede', true),
(1, 'Port Greve', true),
(1, 'Résidence ''t Hof van Haamstede', true),
(1, 'Resort Haamstede', true),
(1, 'Strand Resort Nieuwvliet-Bad', true),
(1, 'Villapark Livingstone', true),
(1, 'Elfstedenhart', true),
(1, 'Esonstad', true),
(1, 'Oan ''e Poel', true),
(1, 'Waterpark De Alde Feanen', true),
(1, 'Waterpark Sneekermeer', true),
(1, 'Waterpark Terherne', true),
(1, 'Natuurdorp Suyderoogh', true),
(1, 'Amerongse Berg', true),
(1, 'Ameland State', true),
(1, 'Beach Park Texel', true),
(1, 'Kaap West', true),
(1, 'Schuttersbos', true),
(1, 'Sluftervallei', true),
(1, 'Villapark Vogelmient', true),
(1, 'Vitamaris', true),
(1, 'Vlieduyn', true),
(1, 'West Terschelling', true),
(2, 'Beach Houses Den Haag', true),
(2, 'Beach Resort Nieuwvliet-Bad', true),
(2, 'Bergresort Winterberg', true),
(2, 'Boomhiemke', true),
(2, 'Bos en Duin', true),
(2, 'Bospark De Schaapskooi', true),
(2, 'Bospark Lunsbergen', true),
(2, 'Bospark ''t Wolfsven', true),
(2, 'Buitenhof Domburg', true),
(2, 'Bungalowpark Hoenderloo', true),
(2, 'Bungalowpark Schin op Geul', true),
(2, 'Camping De Zandput', true),
(2, 'Camping Dishoek', true),
(2, 'Cape Helius', true),
(2, 'Cuber Veluwe', true),
(2, 'De Graaf van Egmont', true),
(2, 'De Heihorsten', true),
(2, 'De Katjeskelder', true),
(2, 'De Soeten Haert', true),
(2, 'De Veluwse Hoevegaerde', true),
(2, 'Duinresort Dunimar', true),
(2, 'Eifelpark Kronenburger See', true),
(2, 'Ferienresort Bad Bentheim', true),
(2, 'Ferienresort Cochem', true),
(2, 'Hafendorf Rheinsberg', true),
(2, 'HANSA-PARK Resort am Meer', true),
(2, 'Hof Domburg', true),
(2, 'Hunzepark', true),
(2, 'Klein Vink', true),
(2, 'Kustpark Egmond aan Zee', true),
(2, 'Kustpark Klein Poelland', true),
(2, 'Kustpark Texel', true),
(2, 'Marber Veluwe', true),
(2, 'Marinapark Volendam', true),
(2, 'Nautisch Centrum Scheveningen', true),
(2, 'Noordzee Résidence Cadzand-Bad', true),
(2, 'Noordzee Résidence De Banjaard', true),
(2, 'Noordzee Résidence Dishoek', true),
(2, 'Noordzee Resort Vlissingen', true),
(2, 'Parkhotel Bad Arcen', true),
(2, 'Recreatiepark De Tolplas', true),
(2, 'Résidence Klein Vink', true),
(2, 'Résidence Wijngaerde', true),
(2, 'Résidence Winterberg', true),
(2, 'Resort Arcen', true),
(2, 'Roompot Ameland', true),
(2, 'Roompot Beach Houses Zandvoort', true),
(2, 'Roompot Beach Resort', true),
(2, 'Roompot Beach Resort Agde', true),
(2, 'Roompot Beach Resort Brouwersdam', true),
(2, 'Roompot Beach Villa''s Hoek van Holland', true),
(2, 'Roompot Bloemendaal aan Zee', true),
(2, 'Roompot Callantsoog', true),
(2, 'Roompot Domein Het Camperveer', true),
(2, 'Roompot ECO Grevelingenstrand', true),
(2, 'Roompot Glamping Lauwersmeer', true),
(2, 'Roompot Gulpen', true),
(2, 'Roompot Lake Resort Brielle', true),
(2, 'Roompot Park De Peel', true),
(2, 'Roompot Park Eksel', true),
(2, 'Roompot Park Veerse Kreek', true),
(2, 'Roompot Résidence De Veerse Wende', true),
(2, 'Roompot Zandvoort', true),
(2, 'St. Pierre', true),
(2, 'Strandhuisjes Julianadorp', true),
(2, 'Strandhuisjes Wijk aan Zee', true),
(2, 'Strandpark Duynhille', true),
(2, 'Strandpark Zeeland', true),
(2, 'Vakantiepark Breeduyn Village', true),
(2, 'Vakantiepark Callassande', true),
(2, 'Vakantiepark Giethoorn', true),
(2, 'Vakantiepark Hunzedal', true),
(2, 'Vakantiepark Kijkduin', true),
(2, 'Vakantiepark Schaijk', true),
(2, 'Villapark De Weerribben', true),
(2, 'Waterpark Belterwiede', true),
(2, 'Waterpark Terkaple', true),
(2, 'Water Village', true),
(2, 'Waterstaete Ossenzijl', true),
(2, 'Weerterbergen', true),
(2, 'Zeebad', true),
(3, 'De Eemhof', true),
(3, 'De Huttenheugte', true),
(3, 'De Kempervennen', true),
(3, 'Het Heijderbos', true),
(3, 'Limburgse Peel', true),
(3, 'Park Zandvoort', true),
(3, 'Port Zélande', true),
(3, 'Parc Sandur', true),
(3, 'Het Meerdal', true),
(4, 'Résidence Valkenburg', true),
(4, 'Resort Veluwe', true),
(4, 'Recreatiepark Noordwijkse Duinen', true),
(4, 'Parc de IJsselhoeve', true),
(4, 'Recreatiepark het Esmeer', true),
(4, 'Recreatiepark de Wielerbaan', true),
(4, 'Recreatiepark Beekbergen', true),
(4, 'Recreatiepark de Woudhoeve', true),
(4, 'Recreatiepark de Scherpenhof', true),
(4, 'Recreatiepark de Bikkels', true),
(4, 'Recreatiepark de Rhederlaagse Meren', true),
(4, 'Recreatiepark het Gelloo', true),
(4, 'Recreatiepark ''t Gelloo', true),
(4, 'Recreatiepark de Paalberg', true),
(4, 'Recreatiepark de Tien Heugten', true),
(4, 'Recreatiepark de Wâldsang', true),
(4, 'Recreatiepark de Riesen', true),
(4, 'Recreatiepark de Elsgraven', true),
(4, 'Recreatiepark de Woudhoeve', true),
(4, 'Recreatiepark het Esmeer', true),
(4, 'Recreatiepark het Hulsbeek', true),
(4, 'Recreatiepark het Rutbeek', true),
(4, 'Recreatiepark het Stoetenslagh', true),
(4, 'Recreatiepark Noordwijkse Duinen', true),
(4, 'Recreatiepark Samoza', true),
(4, 'Recreatiepark TerSpegelt', true),
(4, 'Recreatiepark ''t Veluws Hof', true),
(5, 'De Wije Werelt', true),
(5, 'Resort De Kempen', true),
(5, 'Resort De Rijp', true),
(5, 'Resort De Wije Werelt', true),
(5, 'Resort Limburg', true),
(5, 'Resort Poort van Amsterdam', true),
(5, 'Resort Reestervallei', true),
(5, 'Resort Veluwemeer', true),
(5, 'Resort Zuiderzee', true),
(6, 'Résidence Valkenburg', true),
(6, 'Resort Veluwe', true),
(6, 'Recreatiepark Noordwijkse Duinen', true),
(6, 'Parc de IJsselhoeve', true),
(6, 'Recreatiepark het Esmeer', true),
(6, 'Recreatiepark de Wielerbaan', true),
(6, 'Recreatiepark Beekbergen', true),
(6, 'Recreatiepark de Woudhoeve', true),
(6, 'Recreatiepark de Scherpenhof', true),
(6, 'Recreatiepark de Bikkels', true),
(6, 'Recreatiepark de Rhederlaagse Meren', true),
(6, 'Recreatiepark het Gelloo', true),
(6, 'Recreatiepark ''t Gelloo', true),
(6, 'Recreatiepark de Paalberg', true),
(6, 'Recreatiepark de Tien Heugten', true),
(6, 'Recreatiepark de Wâldsang', true),
(6, 'Recreatiepark de Riesen', true),
(6, 'Recreatiepark de Elsgraven', true),
(6, 'Recreatiepark het Esmeer', true),
(6, 'Recreatiepark het Hulsbeek', true),
(6, 'Recreatiepark het Rutbeek', true),
(6, 'Recreatiepark het Stoetenslagh', true),
(6, 'Recreatiepark Noordwijkse Duinen', true),
(6, 'Recreatiepark Samoza', true),
(6, 'Recreatiepark TerSpegelt', true),
(6, 'Recreatiepark ''t Veluws Hof', true),
(6, 'Recreatiepark ''t Gelloo', true),
(6, 'Recreatiepark ''t Veluws Hof', true),
(8, 'Dormio Waterpark Langelille', true),
(8, 'Dormio Villapark Duynzicht', true),
(8, 'Dormio Park Scorleduyn', true),
(8, 'Dormio Strand Resort Nieuwvliet-Bad', true),
(9, 'Summio Vakantiepark Reevallis', true),
(9, 'Summio Bungalowpark De Riethorst', true),
(9, 'Summio Parc Duc de Brabant', true),
(9, 'Summio Bungalowpark Herperduin', true),
(9, 'Summio Parc Aquadelta', true),
(9, 'Summio Waterpark De Bloemert', true),
(9, 'Summio Havenresort Terherne', true),
(9, 'Summio Buitenplaats De Hildenberg', true),
(9, 'Summio Villaparc Schoonhovenseland', true),
(9, 'Summio Vakantiepark Het Drentse Wold', true),
(9, 'Summio Landgoed Het Grote Zand', true),
(9, 'Summio Villapark Akenveen', true),
(9, 'Summio Vakantiepark It Wiid', true),
(9, 'Summio Waterpark Zwartkruis', true),
(9, 'Summio Vakantiepark Emslandermeer', true),
(9, 'Summio Parc Port Greve', true),
(9, 'Summio Parc De Berkenhorst', true),
(9, 'Summio Duynparc De Heeren van ''s-Gravensande', true),
(9, 'Summio Marina Port Zélande', true);




