// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: costType.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCostType = `-- name: CreateCostType :one
INSERT INTO cost_type (
    description,
    is_deleted
) VALUES (
    $1,
    $2
) RETURNING id, description, is_deleted, created_at, updated_at
`

type CreateCostTypeParams struct {
	Description string      `json:"description"`
	IsDeleted   pgtype.Bool `json:"is_deleted"`
}

func (q *Queries) CreateCostType(ctx context.Context, arg CreateCostTypeParams) (CostType, error) {
	row := q.db.QueryRow(ctx, createCostType, arg.Description, arg.IsDeleted)
	var i CostType
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAllCostType = `-- name: GetAllCostType :many
SELECT id, description, is_deleted, created_at, updated_at FROM cost_type
`

func (q *Queries) GetAllCostType(ctx context.Context) ([]CostType, error) {
	rows, err := q.db.Query(ctx, getAllCostType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CostType{}
	for rows.Next() {
		var i CostType
		if err := rows.Scan(
			&i.ID,
			&i.Description,
			&i.IsDeleted,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
