// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Brand struct {
	ID        int32            `json:"id"`
	Name      string           `json:"name"`
	Logo      pgtype.Text      `json:"logo"`
	Website   pgtype.Text      `json:"website"`
	Validated pgtype.Bool      `json:"validated"`
	IsDeleted pgtype.Bool      `json:"is_deleted"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type CalculationType struct {
	ID          int32            `json:"id"`
	Description string           `json:"description"`
	IsDeleted   pgtype.Bool      `json:"is_deleted"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

type Cost struct {
	ID          int32            `json:"id"`
	CostInputID pgtype.Int4      `json:"cost_input_id"`
	CostTypeID  pgtype.Int4      `json:"cost_type_id"`
	PeriodID    pgtype.Int4      `json:"period_id"`
	Title       string           `json:"title"`
	IsDeleted   pgtype.Bool      `json:"is_deleted"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

type CostCalculation struct {
	ID                  int32            `json:"id"`
	Parkcost            pgtype.Int4      `json:"parkcost"`
	Assetcost           pgtype.Int4      `json:"assetcost"`
	Loancost            pgtype.Int4      `json:"loancost"`
	TaxCost             pgtype.Int4      `json:"tax_cost"`
	AssetValueCost      pgtype.Int4      `json:"asset_value_cost"`
	Revenue             pgtype.Int4      `json:"revenue"`
	TotalCost           pgtype.Int4      `json:"total_cost"`
	Result              pgtype.Int4      `json:"result"`
	ResultPerc          pgtype.Int4      `json:"result_perc"`
	SavingRevenueAmount pgtype.Int4      `json:"saving_revenue_amount"`
	SavingRevenuePerc   pgtype.Int4      `json:"saving_revenue_perc"`
	YieldDiff           pgtype.Int4      `json:"yield_diff"`
	IsDeleted           pgtype.Bool      `json:"is_deleted"`
	CreatedAt           pgtype.Timestamp `json:"created_at"`
	UpdatedAt           pgtype.Timestamp `json:"updated_at"`
}

type CostInput struct {
	ID        int32            `json:"id"`
	Type      string           `json:"type"`
	IsDeleted pgtype.Bool      `json:"is_deleted"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type CostType struct {
	ID          int32            `json:"id"`
	Description string           `json:"description"`
	IsDeleted   pgtype.Bool      `json:"is_deleted"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

type Country struct {
	ID          int32            `json:"id"`
	Iso2        string           `json:"iso2"`
	ShortName   string           `json:"short_name"`
	LongName    string           `json:"long_name"`
	Numcode     pgtype.Text      `json:"numcode"`
	CallingCode string           `json:"calling_code"`
	Cctld       string           `json:"cctld"`
	IsDeleted   pgtype.Bool      `json:"is_deleted"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

type Currency struct {
	ID        int32       `json:"id"`
	Name      string      `json:"name"`
	Symbol    string      `json:"symbol"`
	Isdeleted pgtype.Bool `json:"isdeleted"`
	CreatedAt time.Time   `json:"created_at"`
	UpdatedAt time.Time   `json:"updated_at"`
}

type EntryField struct {
	ID                        int32            `json:"id"`
	CalculationTypeID         int32            `json:"calculation_type_id"`
	UserEmail                 string           `json:"user_email"`
	CalculationDate           pgtype.Date      `json:"calculation_date"`
	ParkID                    int32            `json:"park_id"`
	AssetValue                pgtype.Int4      `json:"asset_value"`
	InventoryValue            pgtype.Int4      `json:"inventory_value"`
	TaxAssetValue             pgtype.Int4      `json:"tax_asset_value"`
	AssetIncreasePercentage   pgtype.Int4      `json:"asset_increase_percentage"`
	ParkHomeNumber            pgtype.Int4      `json:"park_home_number"`
	Vat                       pgtype.Bool      `json:"vat"`
	Ground                    pgtype.Bool      `json:"ground"`
	Squarem2                  pgtype.Int4      `json:"squarem2"`
	ConstructionsYear         pgtype.Date      `json:"constructions_year"`
	RenovationPercentage      pgtype.Int4      `json:"renovation_percentage"`
	YearlyRevenue             pgtype.Int4      `json:"yearly_revenue"`
	YearlyRevenueIncreasePerc pgtype.Int4      `json:"yearly_revenue_increase_perc"`
	AssetLoan                 pgtype.Int4      `json:"asset_loan"`
	LoanInterest              pgtype.Int4      `json:"loan_interest"`
	IsDeleted                 pgtype.Bool      `json:"is_deleted"`
	CreatedAt                 pgtype.Timestamp `json:"created_at"`
	UpdatedAt                 pgtype.Timestamp `json:"updated_at"`
}

type EntryFieldsCost struct {
	ID           int32            `json:"id"`
	CostID       int32            `json:"cost_id"`
	EntryFieldID int32            `json:"entry_field_id"`
	IsDeleted    pgtype.Bool      `json:"is_deleted"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}

type Park struct {
	ID        int32            `json:"id"`
	BrandID   int32            `json:"brand_id"`
	Name      string           `json:"name"`
	CountryID pgtype.Int4      `json:"country_id"`
	Validated pgtype.Bool      `json:"validated"`
	IsDeleted pgtype.Bool      `json:"is_deleted"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type Period struct {
	ID        int32            `json:"id"`
	Period    string           `json:"period"`
	IsDeleted pgtype.Bool      `json:"is_deleted"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type Permission struct {
	ID         int32            `json:"id"`
	Name       string           `json:"name"`
	Permission string           `json:"permission"`
	IsDeleted  pgtype.Bool      `json:"is_deleted"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	UpdatedAt  pgtype.Timestamp `json:"updated_at"`
}

type Role struct {
	ID          int32            `json:"id"`
	Name        string           `json:"name"`
	Description pgtype.Text      `json:"description"`
	IsDeleted   pgtype.Bool      `json:"is_deleted"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

type RolesPermission struct {
	ID           int32            `json:"id"`
	RoleID       int32            `json:"role_id"`
	PermissionID int32            `json:"permission_id"`
	IsDeleted    pgtype.Bool      `json:"is_deleted"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}

type StaticValue struct {
	ID           int32            `json:"id"`
	CostInputID  int32            `json:"cost_input_id"`
	Description  string           `json:"description"`
	Value        float64          `json:"value"`
	IsPercentage pgtype.Bool      `json:"is_percentage"`
	IsDeleted    pgtype.Bool      `json:"is_deleted"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}
