// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import (
	"context"
)

type Querier interface {
	CreateBrand(ctx context.Context, arg CreateBrandParams) (Brand, error)
	CreateCalculationType(ctx context.Context, arg CreateCalculationTypeParams) (CalculationType, error)
	CreateCost(ctx context.Context, arg CreateCostParams) (Cost, error)
	CreateCostCalculation(ctx context.Context, arg CreateCostCalculationParams) (CostCalculation, error)
	CreateCostInput(ctx context.Context, arg CreateCostInputParams) (CostInput, error)
	CreateCostType(ctx context.Context, arg CreateCostTypeParams) (CostType, error)
	CreateCountry(ctx context.Context, arg CreateCountryParams) (Country, error)
	CreateEntryField(ctx context.Context, arg CreateEntryFieldParams) (EntryField, error)
	CreateEntryFieldCost(ctx context.Context, arg CreateEntryFieldCostParams) (EntryFieldsCost, error)
	CreatePark(ctx context.Context, arg CreateParkParams) (Park, error)
	CreatePeriod(ctx context.Context, arg CreatePeriodParams) (Period, error)
	CreatePermission(ctx context.Context, arg CreatePermissionParams) (Permission, error)
	CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error)
	CreateRolePermission(ctx context.Context, arg CreateRolePermissionParams) (RolesPermission, error)
	CreateStaticValues(ctx context.Context, arg CreateStaticValuesParams) (StaticValue, error)
	DeleteCountry(ctx context.Context, id int32) (Country, error)
	DeletePermission(ctx context.Context, id int32) (Permission, error)
	DeleteRole(ctx context.Context, id int32) (Role, error)
	DeleteRolePermission(ctx context.Context, id int32) (RolesPermission, error)
	GetAllBrand(ctx context.Context) ([]Brand, error)
	GetAllCalculationType(ctx context.Context) ([]CalculationType, error)
	GetAllCost(ctx context.Context) ([]Cost, error)
	GetAllCostCalculation(ctx context.Context) ([]CostCalculation, error)
	GetAllCostInput(ctx context.Context) ([]CostInput, error)
	GetAllCostType(ctx context.Context) ([]CostType, error)
	GetAllCountries(ctx context.Context) ([]Country, error)
	GetAllEntryField(ctx context.Context) ([]EntryField, error)
	GetAllEntryFieldCost(ctx context.Context) ([]EntryFieldsCost, error)
	GetAllPark(ctx context.Context) ([]Park, error)
	GetAllPeriod(ctx context.Context) ([]Period, error)
	GetAllPermissions(ctx context.Context) ([]Permission, error)
	GetAllRolePermissions(ctx context.Context) ([]RolesPermission, error)
	GetAllRoles(ctx context.Context) ([]Role, error)
	GetAllStaticValues(ctx context.Context) ([]StaticValue, error)
	GetCountry(ctx context.Context, id int32) (Country, error)
	GetParksByBrand(ctx context.Context, brandID int32) ([]Park, error)
	GetPermission(ctx context.Context, id int32) (Permission, error)
	GetRole(ctx context.Context, id int32) (Role, error)
	GetRolePermission(ctx context.Context, id int32) (RolesPermission, error)
	UpdateCountry(ctx context.Context, arg UpdateCountryParams) (Country, error)
	UpdatePermission(ctx context.Context, arg UpdatePermissionParams) (Permission, error)
	UpdateRole(ctx context.Context, arg UpdateRoleParams) (Role, error)
	UpdateRolePermission(ctx context.Context, arg UpdateRolePermissionParams) (RolesPermission, error)
}

var _ Querier = (*Queries)(nil)
